GameHub/Controllers/CategoriesController.cs
using GameHub.Helpers;
using GameHub.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace GameHub.Controllers
{
    public class CategoriesController : Controller
    {
        private AppDBContext db = new AppDBContext();

        // GET: Categories
        public ActionResult Index()
        {
            if (!AuthHelper.IsAdmin(Session))
            {
                return new HttpStatusCodeResult(403); // Forbidden
            }
            return View(db.Categories.ToList());
        }

        // GET: Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            if (!AuthHelper.IsAdmin(Session))
            {
                return new HttpStatusCodeResult(403); // Forbidden
            }
            return View(category);
        }

        // GET: Categories/Create
        public ActionResult Create()
        {
            if (!AuthHelper.IsAdmin(Session))
            {
                return new HttpStatusCodeResult(403); // Forbidden
            }
            return View();
        }

        // POST: Categories/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CategoryId,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (!AuthHelper.IsAdmin(Session))
            {
                return new HttpStatusCodeResult(403); // Forbidden
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CategoryId,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (!AuthHelper.IsAdmin(Session))
            {
                return new HttpStatusCodeResult(403); // Forbidden
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GameHub/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GameHub.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult About()
        {
            return View();
        }
        public ActionResult Contact()
        {
            return View();
        }
    }
}

GameHub/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GameHub.Models;
using GameHub.Helpers;

namespace GameHub.Controllers
{
    public class UsersController : Controller
    {
        private AppDBContext db = new AppDBContext();

        // GET: Users
        public ActionResult Index()
        {
            if (!AuthHelper.IsAdmin(Session))
            {
                return new HttpStatusCodeResult(403); // Forbidden
            }
            return View(db.Users.ToList());
        }

        // GET: Users/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (!AuthHelper.IsAdmin(Session))
            {
                return new HttpStatusCodeResult(403); // Forbidden
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            if (!AuthHelper.IsAdmin(Session))
            {
                return new HttpStatusCodeResult(403); // Forbidden
            }
            return View();
        }

        // POST: Users/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "userId,username,emailAddress, password, isAdmin")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (!AuthHelper.IsAdmin(Session))
            {
                return new HttpStatusCodeResult(403); // Forbidden
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id)
        {
            var userToUpdate = db.Users.Find(id);
            if (TryUpdateModel(userToUpdate, "", new string[] { "username", "emailAddress", "password", "isAdmin" }))
            {
                if (ModelState.IsValid)
                {
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return View(userToUpdate);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (!AuthHelper.IsAdmin(Session))
            {
                return new HttpStatusCodeResult(403); // Forbidden
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(string username, string emailAddress, string password)
        {
            if (db.Users.Any(u => u.username == username))
            {
                ViewBag.Error = "Username is taken";
                return View();
            }

            var user = new User
            {
                username = username,
                emailAddress = emailAddress,
                password = password
            };

            db.Users.Add(user);
            db.SaveChanges();

            Session["userId"] = user.userId;
            Session["username"] = user.username;

            return RedirectToAction("Index", "Home");
        }

        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        public ActionResult Login(string username, string password, string returnUrl)
        {
            var user = db.Users.FirstOrDefault(u => u.username == username && u.password == password);
            if (user != null)
            {
                Session["userId"] = user.userId;
                Session["username"] = user.username;
                Session["isAdmin"] = user.isAdmin;

                if (!string.IsNullOrEmpty(returnUrl) && Url.IsLocalUrl(returnUrl))
                {
                    return Redirect(returnUrl);
                }

                return RedirectToAction("Index", "Home");
            }

            ViewBag.Error = "Password or username is incorrect.";
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Index", "Home");
        }


    }
}

GameHub/Views/Home/About.cshtml
@{
    ViewBag.Title = "About Game Hub";
}

<style>
    main {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: flex-start;
        min-height: 100vh;
        font-family: Arial, sans-serif;
        padding: 20px;
        box-sizing: border-box;
        text-align: center;
        position: relative;
    }

    .background-rectangle {
        position: absolute;
        top: 50%;
        left: 50%;
        width: 1170px;
        height: 660px;
        background-color: #FFD1DC;
        border-radius: 25px;
        transform: translate(-50%, -50%);
        z-index: 5;
        box-shadow: 0 4px 15px rgba(255, 128, 160, 0.3);
    }

    .center-rectangle {
        position: absolute;
        top: 50%;
        left: 50%;
        width: 1100px;
        height: 600px;
        background-color: #fffaf3;
        border-radius: 15px;
        box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        transform: translate(-50%, -50%);
        padding: 20px;
        box-sizing: border-box;
        z-index: 10;
        overflow-y: auto;
        color: #3F2E3E;
        text-align: left;
        font-size: 1.2rem;
        font-family: inherit;
        white-space: pre-wrap;
    }

        .center-rectangle p {
            font-size: 1rem;
            line-height: 1.4;
        }

    .info-link {
        margin-top: 720px; /* dostosuj wysokość do własnych potrzeb */
        display: inline-block;
        font-size: 1.1rem;
        color: #3F2E3E;
        background-color: #fffaf3;
        padding: 10px 20px;
        border-radius: 10px;
        box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        text-decoration: none;
        z-index: 20;
        position: relative;
    }

        .info-link:hover {
            background-color: #ffe4ec;
        }
</style>

<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title</h2>
    <h3>@ViewBag.Message</h3>

    <div class="flower-wrapper" aria-label="Opis projektu">
        <div class="background-rectangle"></div>
        <div class="center-rectangle">
            <h2>User Manual for Game Hub Application</h2>

            <h3>1. Introduction</h3>
            <p>Game Hub is a web application that allows you to browse games, track player scores, and manage data. The application is intuitive and designed for both regular users and administrators.</p>

            <h3>2. Login and Registration</h3>
            <p>To use the application, you need to log in or register a new account. The login and registration form is available on n a dedicated panel. After logging in, users gain access to features related to scores and favorite games.</p>

            <h3>3. Browsing Games</h3>
            <p>The "Games" page provides a list of all available games along with their assigned categories.</p>

            <h3>4. Tracking Scores</h3>
            <p>On the "Scores" page, you can browse rankings for individual games. </p>

            <h3>5. Favorite Games</h3>
            <p>Each user can mark their favorite games for quick access in the future.</p>

            <h3>6. Administrator Panel</h3>
            <p>If you have administrator privileges, after logging in you will see the admin panel on the main page.</p>

            <h3>7. Navigation in the Application</h3>
            <p>The main menu is available on every page, enabling easy access to Games, Scores, Categories, and user settings. Buttons are intuitively labeled to facilitate the use of the application.</p>

            <h3>8. Tips and Help</h3>
            <p>All interactive elements have tooltips that appear when you hover your mouse over them. If you experience problems with logging in or using the application, please contact the system administrator.</p>
        </div>
    </div>

    <a class="info-link" href="https://docs.google.com/document/d/1sHedoJksyylK7mbyRlRQHFHHcaZgSZBZlcyqx5mU9f0/edit?usp=sharing" target="_blank" rel="noopener noreferrer">
        More info about Game hub
    </a>
</main>

GameHub/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        Game Hub Center<br />
        Krakow, 30-072<br />
        <abbr title="Phone">P:</abbr>
        123 456 789
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@agh.edu.pl">Support@agh.edu.pl</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@agh.edu.pl">Marketing@agh.edu.pl</a>
    </address>
</main>

GameHub/Views/Home/Index.cshtml
@using GameHub.Helpers
@{
    ViewBag.Title = "Index";
}

<style>
    html, body {
        height: 100%;
        margin: 0;
        background-color: #FFF0F3;
        font-family: 'Orbitron', sans-serif;
        user-select: none;
        color: #3F2E3E;
    }

    .center-container {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: flex-start;
        height: 100vh;
        padding-top: 30vh;
        text-align: center;
    }

    .logo-row {
        display: flex;
        align-items: center;
        gap: 0.35em;
        font-size: 8vw;
        color: #3F2E3E;
        transition: color 0.3s ease;
        user-select: none;
    }

    .center-container:hover .logo-row {
        color: #FFD1DC;
    }

    .tooltip-text {
        font-size: 1.5vw;
        color: #3F2E3E;
        margin-top: 10px;
        letter-spacing: 1px;
    }

    .btn-row {
        margin-top: 1rem;
        display: flex;
        justify-content: center;
        gap: 15px; 


    .btn-primary {
        min-width: 120px;
        font-size: 1.25rem;
        padding: 0.5rem 1.5rem;
    }
</style>

<div class="center-container">
    <div class="logo-wrapper" title="Your game center!">
        <div class="logo-row">
            <i class="bi bi-cursor"></i>
            <span>Game Hub</span>
        </div>
        <div class="tooltip-text">Your game center!</div>
    </div>

    <div class="btn-row">
        <a href="/Games/Browse" class="btn btn-primary">Games</a>
        <a href="/Scores/Results" class="btn btn-primary">Scores</a>
    </div>
</div>

@if (AuthHelper.IsAdmin(Session))
{
    <div class="admin-panel mt-4 text-center">
        <h3>Admin panel</h3>
        <div class="btn-group">
            <a href="@Url.Action("Index", "Users")" class="btn btn-outline-primary m-1">Users</a>
            <a href="@Url.Action("Index", "Games")" class="btn btn-outline-success m-1">Games</a>
            <a href="@Url.Action("Index", "Scores")" class="btn btn-outline-secondary m-1">Scores</a>
            <a href="@Url.Action("Index", "Categories")" class="btn btn-outline-secondary m-1">Categories</a>
        </div>
    </div>
}